Repository openAOD/Python-PatternHouse, pull requests merged in 2021-12, with the labels that each got.

#870 Create alphabeticpattern10.py
  Alphabetic Patterns/alphabeticpattern10.py
Labels: SWoC-21

#871 Pyramid pattern 6 and 26
  Alphabetic Patterns/alphabeticpattern11.py
  Numeric Patterns/numericpattern26.py
  Numeric Patterns/numericpattern34.py
  Pyramid Patterns/pyramidpattern12.py
  Pyramid Patterns/pyramidpattern26.py
  Pyramid Patterns/pyramidpattern31.py
  Pyramid Patterns/pyramidpattern36.py
  Pyramid Patterns/pyramidpattern43,py
  Pyramid Patterns/pyramidpattern53.py
  Pyramid Patterns/pyramidpattern6.py
Labels: SWoC-21, beginner

#874 Alphabetic Patterns - Python
  Alphabetic Patterns/alphabeticpattern12.py
  Alphabetic Patterns/alphabeticpattern13.py
  Alphabetic Patterns/alphabeticpattern14.py
  Alphabetic Patterns/alphabeticpattern16.py
  Alphabetic Patterns/alphabeticpattern17.py
  Alphabetic Patterns/alphabeticpattern18.py
  Alphabetic Patterns/alphabeticpattern24.py
  Alphabetic Patterns/alphabeticpattern32.py
  Alphabetic Patterns/alphabeticpattern38.py
  Alphabetic Patterns/alphabeticpattern45.py
Labels: SWoC-21, beginner

#873 Anshyyy
  Alphabetic Patterns/alphabeticpattern140.py
  Alphabetic Patterns/alphabeticpattern141.py
  Alphabetic Patterns/alphabeticpattern142.py
  Alphabetic Patterns/alphabeticpattern163.py
  Alphabetic Patterns/alphabeticpattern164.py
  Alphabetic Patterns/alphabeticpattern165.py
  Alphabetic Patterns/alphabeticpattern166.py
  Alphabetic Patterns/alphabeticpattern167.py
  Alphabetic Patterns/alphabeticpattern168.py
  Alphabetic Patterns/alphabeticpattern189.py
  Alphabetic Patterns/alphabeticpattern190.py
  Alphabetic Patterns/alphabeticpattern191.py
Labels: SWoC-21, beginner

#875 Anshyyy
  Alphabetic Patterns/alphabeticpattern143.py
  Alphabetic Patterns/alphabeticpattern144.py
  Alphabetic Patterns/alphabeticpattern145.py
  Alphabetic Patterns/alphabeticpattern146.py
  Alphabetic Patterns/alphabeticpattern147.py
  Alphabetic Patterns/alphabeticpattern148.py
  Alphabetic Patterns/alphabeticpattern149.py
  Alphabetic Patterns/alphabeticpattern169.py
  Alphabetic Patterns/alphabeticpattern170.py
  Alphabetic Patterns/alphabeticpattern171.py
  Alphabetic Patterns/alphabeticpattern172.py
  Alphabetic Patterns/alphabeticpattern173.py
  Alphabetic Patterns/alphabeticpattern174.py
  Alphabetic Patterns/alphabeticpattern175.py
Labels: SWoC-21, beginner

#876 Anshyyy
  Alphabetic Patterns/alphabeticpattern150.py
  Alphabetic Patterns/alphabeticpattern151.py
  Alphabetic Patterns/alphabeticpattern152.py
  Alphabetic Patterns/alphabeticpattern153.py
  Alphabetic Patterns/alphabeticpattern154.py
  Alphabetic Patterns/alphabeticpattern176.py
  Alphabetic Patterns/alphabeticpattern177.py
  Alphabetic Patterns/alphabeticpattern178.py
  Alphabetic Patterns/alphabeticpattern179.py
  Alphabetic Patterns/alphabeticpattern180.py
Labels: SWoC-21, beginner

#877 Anshyyy
  Alphabetic Patterns/alphabeticpattern155.py
  Alphabetic Patterns/alphabeticpattern156.py
  Alphabetic Patterns/alphabeticpattern157.py
  Alphabetic Patterns/alphabeticpattern158.py
  Alphabetic Patterns/alphabeticpattern159.py
  Alphabetic Patterns/alphabeticpattern181.py
  Alphabetic Patterns/alphabeticpattern182.py
  Alphabetic Patterns/alphabeticpattern183.py
  Alphabetic Patterns/alphabeticpattern184.py
  Alphabetic Patterns/alphabeticpattern185.py
Labels: SWoC-21, beginner

#878 Pattern106 116
  Symbol Patterns/symbolpattern107.py
  Symbol Patterns/symbolpattern108.py
  Symbol Patterns/symbolpattern109.py
  Symbol Patterns/symbolpattern110.py
  Symbol Patterns/symbolpattern111.py
  Symbol Patterns/symbolpattern112.py
  Symbol Patterns/symbolpattern113.py
  Symbol Patterns/symbolpattern114.py
  Symbol Patterns/symbolpattern115.py
  Symbol Patterns/symbolpattern116.py
Labels: SWoC-21, beginner

#879 Anshyyy
  Alphabetic Patterns/alphabeticpattern160.py
  Alphabetic Patterns/alphabeticpattern161.py
  Alphabetic Patterns/alphabeticpattern162.py
  Alphabetic Patterns/alphabeticpattern186.py
  Alphabetic Patterns/alphabeticpattern187.py
  Alphabetic Patterns/alphabeticpattern188.py
  Symbol Patterns/symbolpattern181.py
  Symbol Patterns/symbolpattern182.py
  Symbol Patterns/symbolpattern183.py
  Symbol Patterns/symbolpattern184.py
Labels: SWoC-21, pending

#880 Solved various issues
  Numeric Patterns/numericpattern41.py
  Numeric Patterns/numericpattern44.py
  Numeric Patterns/numericpattern45.py
  Numeric Patterns/numericpattern48.py
  Numeric Patterns/numericpattern49.py
  Numeric Patterns/numericpattern50.py
  Numeric Patterns/numericpattern57.py
  Numeric Patterns/numericpattern58.py
  Numeric Patterns/numericpattern59.py
  Numeric Patterns/numericpattern60.py
Labels: SWoC-21, beginner
