Repository openAOD/Python-PatternHouse, pull requests merged in 2022-02, with the labels that each got.

#908 Solved code for 10 more patterns
  Numeric Patterns/numericpattern107.py
  Numeric Patterns/numericpattern108.py
  Numeric Patterns/numericpattern109.py
  Numeric Patterns/numericpattern110.py
  Numeric Patterns/numericpattern111.py
  Numeric Patterns/numericpattern112.py
  Numeric Patterns/numericpattern113.py
  Numeric Patterns/numericpattern114.py
  Numeric Patterns/numericpattern115.py
  Numeric Patterns/numericpattern129.py
Labels: SWoC-21, beginner

#907 Symbol Pattern
  Symbol Patterns/symbolpattern100.py
  Symbol Patterns/symbolpattern102.py
  Symbol Patterns/symbolpattern105.py
  Symbol Patterns/symbolpattern106.py
  Symbol Patterns/symbolpattern117.py
  Symbol Patterns/symbolpattern118.py
  Symbol Patterns/symbolpattern119.py
  Symbol Patterns/symbolpattern120.py
  Symbol Patterns/symbolpattern121.py
  Symbol Patterns/symbolpattern123.py
  Symbol Patterns/symbolpattern124.py
  Symbol Patterns/symbolpattern125.py
  Symbol Patterns/symbolpattern126.py
  Symbol Patterns/symbolpattern131.py
  Symbol Patterns/symbolpattern132.py
  Symbol Patterns/symbolpattern133.py
  Symbol Patterns/symbolpattern134.py
  Symbol Patterns/symbolpattern135.py
  Symbol Patterns/symbolpattern136.py
  Symbol Patterns/symbolpattern137.py
  Symbol Patterns/symbolpattern138.py
  Symbol Patterns/symbolpattern139.py
  Symbol Patterns/symbolpattern140.py
  Symbol Patterns/symbolpattern141.py
  Symbol Patterns/symbolpattern142.py
  Symbol Patterns/symbolpattern143.py
  Symbol Patterns/symbolpattern144.py
  Symbol Patterns/symbolpattern145.py
  Symbol Patterns/symbolpattern146.py
  Symbol Patterns/symbolpattern147.py
  Symbol Patterns/symbolpattern148.py
  Symbol Patterns/symbolpattern149.py
  Symbol Patterns/symbolpattern150.py
  Symbol Patterns/symbolpattern151.py
  Symbol Patterns/symbolpattern152.py
  Symbol Patterns/symbolpattern153.py
  Symbol Patterns/symbolpattern163.py
  Symbol Patterns/symbolpattern166.py
  Symbol Patterns/symbolpattern98.py
  Symbol Patterns/symbolpattern99.py
Labels: SWoC-21, hard

#910 Solved code for 10 more issues
  Numeric Patterns/numericpattern124.py
  Numeric Patterns/numericpattern125.py
  Numeric Patterns/numericpattern126.py
  Numeric Patterns/numericpattern127.py
  Numeric Patterns/numericpattern128.py
  Numeric Patterns/numericpattern130.py
  Numeric Patterns/numericpattern131.py
  Numeric Patterns/numericpattern132.py
  Numeric Patterns/numericpattern133.py
  Numeric Patterns/numericpattern134.py
Labels: SWoC-21, beginner

#909 Symbol Patterns and Numeric Patterns
  Numeric Patterns/numericpattern273.py
  Numeric Patterns/numericpattern274.py
  Numeric Patterns/numericpattern275.py
  Numeric Patterns/numericpattern276.py
  Numeric Patterns/numericpattern277.py
  Numeric Patterns/numericpattern278.py
  Numeric Patterns/numericpattern279.py
  Numeric Patterns/numericpattern280.py
  Numeric Patterns/numericpattern281.py
  Numeric Patterns/numericpattern282.py
  Numeric Patterns/numericpattern283.py
  Numeric Patterns/numericpattern284.py
  Numeric Patterns/numericpattern285.py
  Numeric Patterns/numericpattern286.py
  Numeric Patterns/numericpattern287.py
  Numeric Patterns/numericpattern288.py
  Numeric Patterns/numericpattern289.py
  Numeric Patterns/numericpattern292.py
  Numeric Patterns/numericpattern293.py
  Numeric Patterns/numericpattern294.py
  Numeric Patterns/numericpattern295.py
  Numeric Patterns/numericpattern296.py
  Symbol Patterns/symbolpattern101.py
  Symbol Patterns/symbolpattern122.py
  Symbol Patterns/symbolpattern127.py
  Symbol Patterns/symbolpattern128.py
  Symbol Patterns/symbolpattern129.py
  Symbol Patterns/symbolpattern130.py
  Symbol Patterns/symbolpattern94.py
  Symbol Patterns/symbolpattern97.py
Labels: SWoC-21, medium

#911 Numeric Patterns
  Numeric Patterns/numericpattern223.py
  Numeric Patterns/numericpattern224.py
  Numeric Patterns/numericpattern225.py
  Numeric Patterns/numericpattern226.py
  Numeric Patterns/numericpattern227.py
  Numeric Patterns/numericpattern228.py
  Numeric Patterns/numericpattern229.py
  Numeric Patterns/numericpattern230.py
  Numeric Patterns/numericpattern231.py
  Numeric Patterns/numericpattern234.py
  Numeric Patterns/numericpattern235.py
  Numeric Patterns/numericpattern236.py
  Numeric Patterns/numericpattern238.py
  Numeric Patterns/numericpattern239.py
  Numeric Patterns/numericpattern240.py
  Numeric Patterns/numericpattern241.py
  Numeric Patterns/numericpattern242.py
  Numeric Patterns/numericpattern243.py
  Numeric Patterns/numericpattern244.py
  Numeric Patterns/numericpattern245.py
  Numeric Patterns/numericpattern246.py
  Numeric Patterns/numericpattern247.py
  Numeric Patterns/numericpattern248.py
  Numeric Patterns/numericpattern249.py
  Numeric Patterns/numericpattern250.py
  Numeric Patterns/numericpattern251.py
  Numeric Patterns/numericpattern252.py
  Numeric Patterns/numericpattern253.py
  Numeric Patterns/numericpattern254.py
  Numeric Patterns/numericpattern255.py
  Numeric Patterns/numericpattern256.py
  Numeric Patterns/numericpattern257.py
  Numeric Patterns/numericpattern258.py
  Numeric Patterns/numericpattern259.py
  Numeric Patterns/numericpattern264.py
  Numeric Patterns/numericpattern265.py
  Numeric Patterns/numericpattern269.py
  Numeric Patterns/numericpattern270.py
  Numeric Patterns/numericpattern271.py
  Numeric Patterns/numericpattern272.py
Labels: SWoC-21, hard

#912 Numeric Patterns
  Numeric Patterns/numericpattern183.py
  Numeric Patterns/numericpattern184.py
  Numeric Patterns/numericpattern185.py
  Numeric Patterns/numericpattern186.py
  Numeric Patterns/numericpattern187.py
  Numeric Patterns/numericpattern188.py
  Numeric Patterns/numericpattern189.py
  Numeric Patterns/numericpattern190.py
  Numeric Patterns/numericpattern191.py
  Numeric Patterns/numericpattern192.py
  Numeric Patterns/numericpattern193.py
  Numeric Patterns/numericpattern194.py
  Numeric Patterns/numericpattern195.py
  Numeric Patterns/numericpattern196.py
  Numeric Patterns/numericpattern197.py
  Numeric Patterns/numericpattern198.py
  Numeric Patterns/numericpattern199.py
  Numeric Patterns/numericpattern200.py
  Numeric Patterns/numericpattern201.py
  Numeric Patterns/numericpattern202.py
  Numeric Patterns/numericpattern203.py
  Numeric Patterns/numericpattern204.py
  Numeric Patterns/numericpattern205.py
  Numeric Patterns/numericpattern206.py
  Numeric Patterns/numericpattern207.py
  Numeric Patterns/numericpattern208.py
  Numeric Patterns/numericpattern209.py
  Numeric Patterns/numericpattern210.py
  Numeric Patterns/numericpattern211.py
  Numeric Patterns/numericpattern212.py
  Numeric Patterns/numericpattern213.py
  Numeric Patterns/numericpattern214.py
  Numeric Patterns/numericpattern215.py
  Numeric Patterns/numericpattern216.py
  Numeric Patterns/numericpattern217.py
  Numeric Patterns/numericpattern218.py
  Numeric Patterns/numericpattern219.py
  Numeric Patterns/numericpattern220.py
  Numeric Patterns/numericpattern221.py
  Numeric Patterns/numericpattern222.py
Labels: SWoC-21, hard

#914 Numeric Patterns
  Alphabetic Patterns/alphabeticpattern101.py
  Alphabetic Patterns/alphabeticpattern102.py
  Alphabetic Patterns/alphabeticpattern103.py
  Alphabetic Patterns/alphabeticpattern104.py
  Alphabetic Patterns/alphabeticpattern105.py
  Alphabetic Patterns/alphabeticpattern106.py
  Alphabetic Patterns/alphabeticpattern107.py
  Alphabetic Patterns/alphabeticpattern108.py
  Alphabetic Patterns/alphabeticpattern109.py
  Alphabetic Patterns/alphabeticpattern46.py
  Alphabetic Patterns/alphabeticpattern47.py
  Alphabetic Patterns/alphabeticpattern48.py
  Alphabetic Patterns/alphabeticpattern49.py
  Alphabetic Patterns/alphabeticpattern50.py
  Alphabetic Patterns/alphabeticpattern51.py
  Alphabetic Patterns/alphabeticpattern52.py
  Alphabetic Patterns/alphabeticpattern53.py
  Numeric Patterns/numericpattern116.py
  Numeric Patterns/numericpattern117.py
  Numeric Patterns/numericpattern118.py
  Numeric Patterns/numericpattern119.py
  Numeric Patterns/numericpattern120.py
  Numeric Patterns/numericpattern121.py
  Numeric Patterns/numericpattern122.py
  Numeric Patterns/numericpattern123.py
  Numeric Patterns/numericpattern139.py
  Numeric Patterns/numericpattern141.py
  Numeric Patterns/numericpattern142.py
  Numeric Patterns/numericpattern143.py
  Numeric Patterns/numericpattern144.py
  Numeric Patterns/numericpattern145.py
  Numeric Patterns/numericpattern147.py
  Pyramid Patterns/pyramidpattern75.py
  Pyramid Patterns/pyramidpattern80.py
  Pyramid Patterns/pyramidpattern81.py
  Pyramid Patterns/pyramidpattern82.py
  Pyramid Patterns/pyramidpattern83.py
  Pyramid Patterns/pyramidpattern84.py
  Pyramid Patterns/pyramidpattern85.py
  Pyramid Patterns/pyramidpattern86.py
Labels: SWoC-21, hard

#915 Pyramid Patterns
  Pyramid Patterns/pyramidpattern55.py
  Pyramid Patterns/pyramidpattern66.py
  Pyramid Patterns/pyramidpattern67.py
  Pyramid Patterns/pyramidpattern68.py
  Pyramid Patterns/pyramidpattern69.py
  Pyramid Patterns/pyramidpattern70.py
  Pyramid Patterns/pyramidpattern71.py
  Pyramid Patterns/pyramidpattern72.py
  Pyramid Patterns/pyramidpattern73.py
  Pyramid Patterns/pyramidpattern74.py
Labels: SWoC-21, beginner

#916 Additional Problems
  Alphabetic Patterns/alphabeticpattern15.py
  Alphabetic Patterns/alphabeticpattern22.py
  Alphabetic Patterns/alphabeticpattern4.py
  Alphabetic Patterns/alphabeticpattern41.py
  Alphabetic Patterns/alphabeticpattern9.py
  Numeric Patterns/numericpattern18.py
  Pyramid Patterns/pyramidpattern93.py
  Symbol Patterns/symbolicpattern103.py
  Symbol Patterns/symbolicpattern104.py
  Symbol Patterns/symbolicpattern93.py
Labels: SWoC-21, beginner
