Repository openAOD/Python-PatternHouse, pull requests merged in 2022-01, with the labels that each got.

#882 Solved symbolic pattern issues
  Symbol Patterns/symbolicpattern20.py
  Symbol Patterns/symbolicpattern21.py
  Symbol Patterns/symbolicpattern22.py
  Symbol Patterns/symbolicpattern23.py
  Symbol Patterns/symbolicpattern24.py
  Symbol Patterns/symbolicpattern25.py
  Symbol Patterns/symbolicpattern26.py
  Symbol Patterns/symbolicpattern27.py
  Symbol Patterns/symbolicpattern28.py
  Symbol Patterns/symbolicpattern29.py
Labels: SWoC-21, beginner

#883 Various issues resolved
  Symbol Patterns/symbolicpattern30.py
  Symbol Patterns/symbolicpattern31.py
  Symbol Patterns/symbolicpattern33.py
  Symbol Patterns/symbolicpattern34.py
  Symbol Patterns/symbolicpattern36.py
  Symbol Patterns/symbolicpattern37.py
  Symbol Patterns/symbolicpattern38.py
  Symbol Patterns/symbolicpattern39.py
  Symbol Patterns/symbolicpattern40.py
  Symbol Patterns/symbolicpattern41.py
  Symbol Patterns/symbolicpattern42.py
  Symbol Patterns/symbolicpattern43.py
  Symbol Patterns/symbolicpattern44.py
  Symbol Patterns/symbolicpattern45.py
  Symbol Patterns/symbolicpattern46.py
  Symbol Patterns/symbolicpattern47.py
  Symbol Patterns/symbolicpattern48.py
  Symbol Patterns/symbolicpattern49.py
  Symbol Patterns/symbolicpattern50.py
  Symbol Patterns/symbolicpattern51.py
Labels: SWoC-21, easy

#884 Anshyyy
  Symbol Patterns/symbolpattern185.py
  Symbol Patterns/symbolpattern186.py
  Symbol Patterns/symbolpattern187.py
  Symbol Patterns/symbolpattern188.py
  Symbol Patterns/symbolpattern189.py
  Symbol Patterns/symbolpattern190.py
  Symbol Patterns/symbolpattern191.py
  Symbol Patterns/symbolpattern192.py
  Symbol Patterns/symbolpattern193.py
  Symbol Patterns/symbolpattern194.py
Labels: SWoC-21, beginner

#887 Committed codes for 10 patterns
  Alphabetic Patterns/alphabeticpattern19.py
  Alphabetic Patterns/alphabeticpattern20.py
  Alphabetic Patterns/alphabeticpattern21.py
  Alphabetic Patterns/alphabeticpattern23.py
  Alphabetic Patterns/alphabeticpattern25.py
  Alphabetic Patterns/alphabeticpattern26.py
  Alphabetic Patterns/alphabeticpattern7.py
  Alphabetic Patterns/alphabeticpattern8.py
  Pyramid Patterns/pyramidpattern61.py
  Symbol Patterns/symbolicpattern162.py
Labels: SWoC-21, beginner

#889 Added Code for 10 More patterns
  Alphabetic Patterns/alphabeticpattern27.py
  Alphabetic Patterns/alphabeticpattern29.py
  Alphabetic Patterns/alphabeticpattern30.py
  Alphabetic Patterns/alphabeticpattern31.py
  Alphabetic Patterns/alphabeticpattern33.py
  Alphabetic Patterns/alphabeticpattern34.py
  Alphabetic Patterns/alphabeticpattern35.py
  Alphabetic Patterns/alphabeticpattern36.py
  Alphabetic Patterns/alphabeticpattern37.py
  Alphabetic Patterns/alphabeticpattern39.py
Labels: SWoC-21, beginner

#888 Anshyyy
  Symbol Patterns/symbolpatter203.py
  Symbol Patterns/symbolpattern195.py
  Symbol Patterns/symbolpattern196.py
  Symbol Patterns/symbolpattern197.py
  Symbol Patterns/symbolpattern198.py
  Symbol Patterns/symbolpattern199.py
  Symbol Patterns/symbolpattern200.py
  Symbol Patterns/symbolpattern201.py
  Symbol Patterns/symbolpattern202.py
  Symbol Patterns/symbolpattern204.py
  Symbol Patterns/symbolpattern205.py
  Symbol Patterns/symbolpattern206.py
Labels: SWoC-21, beginner

#890 Resolved issues
  Symbol Patterns/symbolpattern154.py
  Symbol Patterns/symbolpattern155.py
  Symbol Patterns/symbolpattern156.py
  Symbol Patterns/symbolpattern157.py
  Symbol Patterns/symbolpattern158.py
  Symbol Patterns/symbolpattern159.py
  Symbol Patterns/symbolpattern160.py
  Symbol Patterns/symbolpattern161.py
  Symbol Patterns/symbolpattern67.py
  Symbol Patterns/symbolpattern68.py
Labels: SWoC-21, beginner

#892 Solved 10 more patterns
  Alphabetic Patterns/alphabeticpattern40.py
  Alphabetic Patterns/alphabeticpattern42.py
  Alphabetic Patterns/alphabeticpattern43.py
  Alphabetic Patterns/alphabeticpattern44.py
  Alphabetic Patterns/alphabeticpattern54.py
  Alphabetic Patterns/alphabeticpattern55.py
  Alphabetic Patterns/alphabeticpattern56.py
  Alphabetic Patterns/alphabeticpattern57.py
  Alphabetic Patterns/alphabeticpattern58.py
  Alphabetic Patterns/alphabeticpattern59.py
Labels: SWoC-21, beginner

#894 Solved Code for 10 More patterns
  Alphabetic Patterns/alphabeticpatter66.py
  Alphabetic Patterns/alphabeticpattern60.py
  Alphabetic Patterns/alphabeticpattern61.py
  Alphabetic Patterns/alphabeticpattern62.py
  Alphabetic Patterns/alphabeticpattern63.py
  Alphabetic Patterns/alphabeticpattern64.py
  Alphabetic Patterns/alphabeticpattern65.py
  Alphabetic Patterns/alphabeticpattern67.py
  Alphabetic Patterns/alphabeticpattern68.py
  Alphabetic Patterns/pyramidpattern61.py
Labels: SWoC-21, beginner

#896 Added codes for 10 more patterns
  Alphabetic Patterns/alphabeticpattern70.py
  Alphabetic Patterns/alphabeticpattern71.py
  Alphabetic Patterns/alphabeticpattern72.py
  Alphabetic Patterns/alphabeticpattern73.py
  Alphabetic Patterns/alphabeticpattern74.py
  Alphabetic Patterns/alphabeticpattern75.py
  Alphabetic Patterns/alphabeticpattern76.py
  Alphabetic Patterns/alphabeticpattern77.py
  Alphabetic Patterns/alphabeticpattern78.py
  Alphabetic Patterns/alphabeticpattern79.py
Labels: SWoC-21, beginner

#897 Numeric Pattern in Python.
  Numeric Patterns/numericpattern19.py
  Numeric Patterns/numericpattern20.py
  Numeric Patterns/numericpattern21.py
  Numeric Patterns/numericpattern22.py
  Numeric Patterns/numericpattern23.py
  Numeric Patterns/numericpattern24.py
  Numeric Patterns/numericpattern27.py
  Numeric Patterns/numericpattern28.py
  Numeric Patterns/numericpattern303.py
  Numeric Patterns/numericpattern304.py
  Numeric Patterns/numericpattern305.py
  Numeric Patterns/numericpattern306.py
  Numeric Patterns/numericpattern307.py
  Numeric Patterns/numericpattern308.py
  Numeric Patterns/numericpattern31.py
  Numeric Patterns/numericpattern33.py
  Numeric Patterns/numericpattern35.py
  Numeric Patterns/numericpattern36.py
  Numeric Patterns/numericpattern37.py
  Numeric Patterns/numericpattern61.py
Labels: SWoC-21, easy

#899 Solved code for 10 more patterns
  Alphabetic Patterns/alphabeticpattern80.py
  Numeric Patterns/numericpattern29.py
  Numeric Patterns/numericpattern32.py
  Numeric Patterns/numericpattern38.py
  Numeric Patterns/numericpattern62.py
  Numeric Patterns/numericpattern63.py
  Numeric Patterns/numericpattern64.py
  Numeric Patterns/numericpattern65.py
  Numeric Patterns/numericpattern66.py
  Numeric Patterns/numericpattern67.py
Labels: SWoC-21, beginner

#900 Solved Code for 10 more issues
  Numeric Patterns/numericpattern68.py
  Numeric Patterns/numericpattern69.py
  Numeric Patterns/numericpattern70.py
  Numeric Patterns/numericpattern71.py
  Numeric Patterns/numericpattern72.py
  Numeric Patterns/numericpattern73.py
  Numeric Patterns/numericpattern74.py
  Numeric Patterns/numericpattern75.py
  Numeric Patterns/numericpattern76.py
  Numeric Patterns/numericpattern77.py
Labels: SWoC-21, beginner

#901 Alphabetic and Symbol Patterns
  Alphabetic Patterns/alphabeticpattern100.py
  Alphabetic Patterns/alphabeticpattern134.py
  Alphabetic Patterns/alphabeticpattern135.py
  Alphabetic Patterns/alphabeticpattern136.py
  Alphabetic Patterns/alphabeticpattern137.py
  Alphabetic Patterns/alphabeticpattern138.py
  Alphabetic Patterns/alphabeticpattern139.py
  Alphabetic Patterns/alphabeticpattern81.py
  Alphabetic Patterns/alphabeticpattern82.py
  Alphabetic Patterns/alphabeticpattern83.py
  Alphabetic Patterns/alphabeticpattern84.py
  Alphabetic Patterns/alphabeticpattern85.py
  Alphabetic Patterns/alphabeticpattern86.py
  Alphabetic Patterns/alphabeticpattern87.py
  Alphabetic Patterns/alphabeticpattern88.py
  Alphabetic Patterns/alphabeticpattern89.py
  Alphabetic Patterns/alphabeticpattern90.py
  Alphabetic Patterns/alphabeticpattern91.py
  Alphabetic Patterns/alphabeticpattern92.py
  Alphabetic Patterns/alphabeticpattern93.py
  Alphabetic Patterns/alphabeticpattern94.py
  Alphabetic Patterns/alphabeticpattern95.py
  Alphabetic Patterns/alphabeticpattern96.py
  Alphabetic Patterns/alphabeticpattern97.py
  Alphabetic Patterns/alphabeticpattern98.py
  Alphabetic Patterns/alphabeticpattern99.py
  Pyramid Patterns/pyramidpattern64.py
  Symbol Patterns/symbolpattern12.py
  Symbol Patterns/symbolpattern13.py
  Symbol Patterns/symbolpattern14.py
  Symbol Patterns/symbolpattern15.py
  Symbol Patterns/symbolpattern16.py
  Symbol Patterns/symbolpattern17.py
  Symbol Patterns/symbolpattern18.py
  Symbol Patterns/symbolpattern19.py
  Symbol Patterns/symbolpattern52.py
  Symbol Patterns/symbolpattern53.py
  Symbol Patterns/symbolpattern54.py
  Symbol Patterns/symbolpattern55.py
  Symbol Patterns/symbolpattern56.py
Labels: SWoC-21, hard

#903 Solved Code for 10More patterns
  Numeric Patterns/numericpattern39.py
  Numeric Patterns/numericpattern78.py
  Numeric Patterns/numericpattern79.py
  Numeric Patterns/numericpattern80.py
  Numeric Patterns/numericpattern81.py
  Numeric Patterns/numericpattern82.py
  Numeric Patterns/numericpattern83.py
  Numeric Patterns/numericpattern84.py
  Numeric Patterns/numericpattern85.py
  Numeric Patterns/numericpattern86.py
Labels: SWoC-21, beginner

#904 Solved code for 10 more issues
  Numeric Patterns/numericpattern87.py
  Numeric Patterns/numericpattern88.py
  Numeric Patterns/numericpattern89.py
  Numeric Patterns/numericpattern90.py
  Numeric Patterns/numericpattern91.py
  Numeric Patterns/numericpattern92.py
  Numeric Patterns/numericpattern93.py
  Numeric Patterns/numericpattern94.py
  Numeric Patterns/numericpattern95.py
  numericpattern96.py
Labels: SWoC-21, beginner

#902 Symbol Patterns
  Symbol Patterns/symbolpattern57.py
  Symbol Patterns/symbolpattern58.py
  Symbol Patterns/symbolpattern59.py
  Symbol Patterns/symbolpattern60.py
  Symbol Patterns/symbolpattern61.py
  Symbol Patterns/symbolpattern62.py
  Symbol Patterns/symbolpattern63.py
  Symbol Patterns/symbolpattern64.py
  Symbol Patterns/symbolpattern65.py
  Symbol Patterns/symbolpattern66.py
  Symbol Patterns/symbolpattern69.py
  Symbol Patterns/symbolpattern70.py
  Symbol Patterns/symbolpattern71.py
  Symbol Patterns/symbolpattern72.py
  Symbol Patterns/symbolpattern73.py
  Symbol Patterns/symbolpattern74.py
  Symbol Patterns/symbolpattern75.py
  Symbol Patterns/symbolpattern76.py
  Symbol Patterns/symbolpattern77.py
  Symbol Patterns/symbolpattern78.py
  Symbol Patterns/symbolpattern79.py
  Symbol Patterns/symbolpattern80.py
  Symbol Patterns/symbolpattern81.py
  Symbol Patterns/symbolpattern82.py
  Symbol Patterns/symbolpattern83.py
  Symbol Patterns/symbolpattern84.py
  Symbol Patterns/symbolpattern85.py
  Symbol Patterns/symbolpattern86.py
  Symbol Patterns/symbolpattern87.py
  Symbol Patterns/symbolpattern88.py
Labels: SWoC-21, medium

#905 Solved code for 10 more patterns
  Numeric Patterns/numericpattern100.py
  Numeric Patterns/numericpattern101.py
  Numeric Patterns/numericpattern102.py
  Numeric Patterns/numericpattern103.py
  Numeric Patterns/numericpattern104.py
  Numeric Patterns/numericpattern105.py
  Numeric Patterns/numericpattern106.py
  Numeric Patterns/numericpattern97.py
  Numeric Patterns/numericpattern98.py
  Numeric Patterns/numericpattern99.py
Labels: SWoC-21, beginner

#906 Create Numeric Pattern (297 - 302) and Symbol Pattern
  Numeric Patterns/numericpattern297.py
  Numeric Patterns/numericpattern298.py
  Numeric Patterns/numericpattern299.py
  Numeric Patterns/numericpattern300.py
  Numeric Patterns/numericpattern301.py
  Numeric Patterns/numericpattern302.py
  Symbol Patterns/symbolpattern89.py
  Symbol Patterns/symbolpattern90.py
  Symbol Patterns/symbolpattern95.py
  Symbol Patterns/symbolpattern96.py
Labels: SWoC-21, beginner
